version: '3'

services:
  new-app:
    image: nginx:alpine
    volumes:
      - ./new-app:/usr/share/nginx/html
    ports:
      - "8082:80"
  old-app:
    image: nginx:alpine
    volumes:
      - ./old-app:/usr/share/nginx/html
    ports:
      - "8081:80"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - new-app
      - old-app